In [1]:
import numpy as np  # type: ignore
import pandas as pd  # type: ignore

import fiona  # type: ignore
from fiona.crs import from_epsg # type: ignore
import geopandas as gpd  # type: ignore
import shapely # type: ignore
from shapely.geometry import Point

import matplotlib.pyplot as plt  # type: ignore
import seaborn as sns  # type: ignore


%matplotlib inline

In [2]:
#Read shp file

estsoil_12c = "Data\EstSoil-EH_v1.2c.shp\EstSoil-EH_v1.2c.shp"
data = gpd.read_file(estsoil_12c,encoding='utf-8')

display(data.head())

,orig_fid,est_soilty,wrb_code,wrb_main,est_txcode,nlayers,zmx,z1,est_txt1,lxtype1,...,grassland_,area_wetla,wetland_pc,area_urban,urban_pct,area_water,water_pct,area_other,other_pct,geometry
0,0,Ag,FL-gln,FL,l,1.0,1000.0,1000.0,l,S,...,0.000000,0.0,0.0,0.000000,0.000000,0.066504,0.003678,1808.194742,99.996322,"POLYGON ((698614.390 6447795.940, 698612.523 6..."
1,1,Ag,FL-gln,FL,l,1.0,1000.0,1000.0,l,S,...,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,"POLYGON ((668432.067 6543565.911, 668425.630 6..."
2,2,Ag,FL-gln,FL,l,1.0,1000.0,1000.0,l,S,...,71.058156,0.0,0.0,386.624055,14.876251,359.077009,13.816315,0.000000,0.000000,"POLYGON ((668550.130 6543573.200, 668543.495 6..."
3,3,Ag,FL-gln,FL,l,1.0,1000.0,1000.0,l,S,...,66.551261,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,"POLYGON ((679817.320 6545854.050, 679829.522 6..."
4,4,Ag,FL-gln,FL,l,1.0,1000.0,1000.0,l,S,...,98.280958,0.0,0.0,0.000000,0.000000,28.399424,1.719042,0.000000,0.000000,"POLYGON ((677362.640 6546501.230, 677345.370 6..."

In [3]:
#Drop soc1 soc2 soc3 soc4 values
no_soc_data = data.drop(["soc1","soc2","soc3","soc4"],axis=1)
no_soc_data.columns

Index(['orig_fid', 'est_soilty', 'wrb_code', 'wrb_main', 'est_txcode',
       'nlayers', 'zmx', 'z1', 'est_txt1', 'lxtype1', 'est_crs1', 'sand1',
       'silt1', 'clay1', 'rock1', 'bd1', 'k1', 'awc1', 'z2', 'est_txt2',
       'lxtype2', 'est_crs2', 'sand2', 'silt2', 'clay2', 'rock2', 'bd2', 'k2',
       'awc2', 'z3', 'est_txt3', 'lxtype3', 'est_crs3', 'sand3', 'silt3',
       'clay3', 'rock3', 'bd3', 'k3', 'awc3', 'z4', 'est_txt4', 'lxtype4',
       'est_crs4', 'sand4', 'silt4', 'clay4', 'rock4', 'bd4', 'k4', 'awc4',
       'unit_area', 'tri_mean', 'tri_stdev', 'tri_median', 'twi_mean',
       'twi_stdev', 'twi_median', 'slp_mean', 'slp_stdev', 'slp_median',
       'ls_mean', 'ls_stdev', 'ls_median', 'area_drain', 'drain_pct',
       'area_arabl', 'arable_pct', 'area_fores', 'forest_pct', 'area_grass',
       'grassland_', 'area_wetla', 'wetland_pc', 'area_urban', 'urban_pct',
       'area_water', 'water_pct', 'area_other', 'other_pct', 'geometry'],
      dtype='object')

In [5]:
#Drop all unnecessary columns(ones which are calculated based on previous SOC data and the ones which are already exist in soc_samples data)
#before joining to soc_samples data


# cleaned_data = no_soc_data.drop(['wrb_code','wrb_main', 'nlayers', 'est_txt1', 'lxtype1', 'est_crs1', 'bd1', 'est_txt2', 'lxtype2', 
#                     'est_crs2','bd2','k1','k2','est_txt3', 'lxtype3', 'est_crs3', 'bd3', 'k3', 'est_txt4','lxtype4','est_crs4',
#                        'bd4', 'k4','unit_area', 'tri_mean', 'tri_stdev', 'tri_median', 'twi_mean','twi_stdev', 'twi_median', 
#                        'slp_mean', 'slp_stdev', 'slp_median',  'ls_mean', 'ls_stdev', 'ls_median', 'area_drain', 'drain_pct',
#                        'area_arabl', 'arable_pct', 'area_fores', 'forest_pct', 'area_grass','grassland_', 'area_wetla', 
#                        'wetland_pc', 'area_urban', 'urban_pct','area_water', 'water_pct', 'area_other', 'other_pct', 'geometry',
#                        'awc1', 'awc2', 'awc3', 'awc4' ],axis=1)

cleaned_data.head()

,orig_fid,est_soilty,est_txcode,zmx,z1,sand1,silt1,clay1,rock1,z2,...,z3,sand3,silt3,clay3,rock3,z4,sand4,silt4,clay4,rock4
0,0,Ag,l,1000.0,1000.0,90,5,5,0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,Ag,l,1000.0,1000.0,90,5,5,0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,Ag,l,1000.0,1000.0,90,5,5,0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,Ag,l,1000.0,1000.0,90,5,5,0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,Ag,l,1000.0,1000.0,90,5,5,0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
# read soc data
soc_samples = gpd.read_file('Data\data_deposit_supplements_1.2c\data_deposit_supplements_1.2c\soc_rf_model\soc_rf_redone_3301.gpkg', layer = "soc_train_samples_outrem_origfid_avg")
soc_samples.head()

,orig_fid,SOC_mean,SOC_std,SOC_med,SOC_min,SOC_max,origin,origin_p,s_count,upd_siffer,...,area_other,unit_area,arable_pct,forest_pct,grassland_pct,wetland_pct,urban_pct,water_pct,other_pct,geometry
0,15159,11.078491,0.000559,11.078491,11.078095,11.078886,estonian_alvars_soil_sample_single_dataset.shp,0.500000,2,ArG,...,20363.430457,89012.199332,0.209052,30.211757,45.509613,16.460368,0.000000,1.192456,22.877123,POINT (443390.670 6494246.123)
1,22283,1.056000,0.669724,0.840000,0.440000,2.190000,envir_biosoils_survey.shp,1.000000,5,D,...,0.000000,25583.014316,44.760985,55.239015,0.000000,0.000000,0.000000,0.000000,0.000000,POINT (661204.025 6433312.518)
2,45116,5.339205,NaN,5.339205,5.339205,5.339205,rmk_soil_data.shp,1.000000,1,Dg,...,0.000000,1948.785206,0.000000,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000,POINT (593729.152 6457480.739)
3,86756,1.000000,0.000000,1.000000,1.000000,1.000000,envir_kese_muld_export.shp,1.000000,2,E2o,...,526.615939,62036.861342,82.160218,12.099221,0.000000,0.000000,4.891685,0.000000,0.848876,POINT (644275.296 6425833.836)
4,94817,4.029763,0.851630,3.514495,3.446287,5.128507,estonian_alvars_open_areas.shp,0.166667,6,Gh',...,149612.185454,354413.777500,0.515653,56.275738,0.693469,0.000000,0.035944,0.265209,42.213987,POINT (376404.901 6468198.723)

In [20]:
#merge dataframes of soc file and 
merged_data = pd.merge(cleaned_data, soc_samples, on= "orig_fid")
display(merged_data.sample(50))

,orig_fid,est_soilty,est_txcode,zmx,z1,sand1,silt1,clay1,rock1,z2,...,area_other,unit_area,arable_pct,forest_pct,grassland_pct,wetland_pct,urban_pct,water_pct,other_pct,geometry
408,601041,LP,sl40-70/ls₂,1000.0,550.0,82,9,9,0,1000.0,...,0.000000,5.078975e+04,0.000000,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000,POINT (663776.502 6399418.730)
322,432408,LGn,pl,1000.0,1000.0,90,3,7,0,NaN,...,6664.647752,4.034168e+04,0.000000,81.223991,0.000000,0.000000,2.255509,0.000000,16.520500,POINT (561657.402 6508086.172)
201,302248,KIg,ls₁70/+ls₂,1000.0,700.0,65,20,15,0,1000.0,...,0.000000,2.015549e+05,0.000000,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000,POINT (596547.517 6445786.089)
270,394662,Kr,ls₁10-25/r₄ls₁,1000.0,175.0,65,20,15,0,1000.0,...,95554.888400,4.223413e+06,3.493320,92.901816,0.970948,0.002706,0.375519,0.007071,2.262504,POINT (513245.739 6536889.544)
426,688884,M'',t₃50-100/ls₁,1000.0,750.0,15,15,70,0,1000.0,...,9075.643910,8.064329e+05,0.000000,84.857199,12.798887,1.212201,0.000000,0.006307,1.125406,POINT (697258.000 6457225.000)
200,298210,KIg,v⁰₁sl35/v⁰₁ls₁30-40/v₁ls₁,1000.0,350.0,82,9,9,6,700.0,...,8431.585060,5.376973e+05,86.385576,7.512886,1.877389,0.000000,1.469435,1.186624,1.568091,POINT (654570.272 6479316.878)
204,307554,KIg,v⁰₁ls₁55-90/v₁ls₁,1000.0,725.0,65,20,15,6,1000.0,...,493.784205,9.429586e+05,79.546790,16.404107,1.773416,0.000000,2.155093,0.068228,0.052365,POINT (650191.145 6473486.107)
446,726654,R''',t₁150,1500.0,1500.0,25,25,50,0,NaN,...,0.000000,2.755280e+06,0.000000,1.833028,0.000000,96.934699,0.000000,1.232274,0.000000,POINT (569286.545 6518205.859)
143,259284,Kh'',r₂sl25-28/p,1000.0,265.0,82,9,9,15,1000.0,...,194.471586,6.669386e+04,0.092075,87.054921,10.565128,0.000000,1.996287,0.000000,0.291588,POINT (476458.187 6490946.034)
118,246815,Kg,r₂sl30/r₄sl,1000.0,300.0,82,9,9,15,1000.0,...,2668.642048,3.406736e+05,1.828750,95.641061,1.103003,0.643843,0.000000,0.000000,0.783343,POINT (377199.969 6465730.631)
37,137468,GI1,l,1000.0,1000.0,90,5,5,0,NaN,...,0.000000,1.179300e+04,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,POINT (675767.645 6434858.181)
245,377738,Kr,kb₃sl35/r₄sl20/p,1000.0,350.0,82,9,9,25,550.0,...,2047.592797,8.264935e+04,47.437657,46.465884,1.070241,0.000000,1.948620,0.600153,2.477446,POINT (471936.613 6500352.040)
414,638352,LPg,v⁰₁sl60-70/v⁰₁ls₁,1000.0,650.0,82,9,9,6,1000.0,...,510.768237,3.407881e+05,94.337343,2.390855,0.019567,0.000000,3.065983,0.036374,0.149879,POINT (674815.683 6432711.438)
428,707770,M''',t₂30-50/t₁125,1650.0,400.0,20,20,60,0,1650.0,...,75259.510472,1.925008e+07,38.778670,32.089060,2.361188,25.971236,0.000122,0.408889,0.390957,POINT (494079.333 6493164.333)
99,231338,K,r₂ls₁35-40/r₄ls₁,1000.0,375.0,65,20,15,15,1000.0,...,0.000000,1.738197e+05,56.972330,36.899939,4.735426,0.000000,1.392306,0.000000,0.000000,POINT (545548.568 6570360.907)
194,282523,KI,v⁰₁sl/ls₁,1000.0,500.0,82,9,9,6,1000.0,...,0.000000,1.363415e+04,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,POINT (652124.357 6479984.335)
158,260783,Kh'',sl10/r₄sl,1000.0,100.0,82,9,9,0,1000.0,...,33630.652729,1.688189e+06,0.000000,83.798178,12.049891,0.129448,1.997218,0.061295,1.992114,POINT (373037.229 6473482.371)
290,405790,L(k)Ig,l150,1500.0,1500.0,90,5,5,0,NaN,...,0.000000,1.616261e+04,0.000000,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000,POINT (551112.875 6453294.170)
207,315600,KIg,v⁰₁ls₁60-80/r₂ls₂,1000.0,700.0,65,20,15,6,1000.0,...,8457.323209,8.867801e+05,66.935133,14.220673,13.603230,0.000000,4.291399,0.127823,0.953711,POINT (611783.749 6498941.681)
351,507193,LkI,l/ls₂,1000.0,500.0,90,5,5,0,1000.0,...,0.000000,6.364629e+03,0.000000,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000,POINT (695994.976 6414176.786)
468,745489,TxR,t₁150,1500.0,1500.0,25,25,50,0,NaN,...,972.616247,5.634159e+05,0.000000,0.488021,0.000000,97.781608,0.000000,1.557742,0.172628,POINT (659337.913 6422417.387)
259,383362,Kr,r₃sl,1000.0,1000.0,82,9,9,25,NaN,...,1742.706668,8.045601e+04,23.700335,57.781426,16.352203,0.000000,0.000000,0.000000,2.166037,POINT (480812.595 6492600.800)
175,262511,Kh''g,sl,1000.0,1000.0,82,9,9,0,NaN,...,2316.003793,1.036674e+05,0.000000,60.594351,34.870427,0.000000,2.301150,0.000000,2.234072,POINT (426626.965 6472769.222)
195,284161,KI,v⁰₂sl40/v⁰₂ls₂30/v₂ls₂,1000.0,400.0,82,9,9,15,700.0,...,0.000000,1.684287e+05,0.000000,88.555815,11.283904,0.000000,0.224710,0.000000,0.000000,POINT (673238.318 6472702.367)
12,95873,Gh'',v⁰₁ls₁25-30/p,1000.0,275.0,65,20,15,6,1000.0,...,0.000000,7.983111e+04,0.000000,47.339356,52.660644,0.000000,0.000000,0.000000,0.000000,POINT (574155.303 6593752.692)
240,377568,Kr,kb₃sl30/p,1000.0,300.0,82,9,9,25,1000.0,...,408.308121,3.105064e+05,34.300158,20.997634,40.442379,0.000000,4.156324,0.000000,0.131498,POINT (460185.090 6501320.301)
437,726463,R''',t₁150,1500.0,1500.0,25,25,50,0,NaN,...,0.000000,4.222316e+06,0.000000,0.009677,0.000000,99.934370,0.000000,0.055953,0.000000,POINT (697423.057 6457618.804)
243,377717,Kr,kb₃sl/p,1000.0,500.0,82,9,9,25,1000.0,...,3280.019743,3.606506e+04,0.000000,87.732068,3.173201,0.000000,0.000000,0.000000,9.094731,POINT (471944.030 6500239.674)
10,95445,Gh'',r₂ls₂10-30/p,1000.0,200.0,55,30,15,15,1000.0,...,119551.290266,1.669773e+06,0.000000,45.637767,39.374378,0.000000,7.829061,0.031198,7.159734,POINT (518935.006 6584721.136)
262,385187,Kr,r₄ls₁,1000.0,1000.0,65,20,15,40,NaN,...,31852.392785,5.790360e+05,12.444007,74.518214,5.596751,0.000000,1.884216,0.062332,5.500935,POINT (447195.932 6497048.079)
50,153090,Gkr,r₃ls20-40/p,1000.0,300.0,55,30,15,25,1000.0,...,443.962557,5.051233e+05,0.000000,59.429500,39.579002,0.000000,0.068825,0.834781,0.087892,POINT (508897.189 6578501.328)
457,734664,S'',t₂60-90/ls₂,1000.0,750.0,20,20,60,0,1000.0,...,0.000000,1.306402e+05,12.854716,83.379202,0.000000,3.766081,0.000000,0.000000,0.000000,POINT (561409.105 6440332.438)
347,503968,LkI,sl90/l,1000.0,900.0,82,9,9,0,1000.0,...,5483.751067,3.657461e+04,0.000000,85.006673,0.000000,0.000000,0.000000,0.000000,14.993327,POINT (645025.583 6432687.321)
269,394642,Kr,kb₃l10/kb,1000.0,100.0,90,5,5,25,1000.0,...,23016.051542,1.557656e+05,0.000000,49.874668,35.293078,0.056170,0.422692,0.000000,14.776085,POINT (466748.923 6571664.663)
397,583228,LP,sl80/ls₂,1000.0,800.0,82,9,9,0,1000.0,...,4460.245993,2.547022e+05,0.000000,92.003938,0.000000,3.323366,2.921534,0.000000,1.751161,POINT (651803.131 6435067.080)
278,438089,LI,l200,2000.0,2000.0,90,5,5,0,NaN,...,0.000000,1.830652e+05,0.000000,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000,POINT (699422.911 6423483.748)
424,687528,M'',t₃150,1500.0,1500.0,15,15,70,0,NaN,...,8731.611703,1.682698e+05,4.982753,30.341192,24.885138,33.710313,0.371908,0.519641,5.189056,POINT (665489.200 6459004.100)
7,95094,Gh'',r₁l30/p,1000.0,300.0,90,5,5,6,1000.0,...,0.000000,4.690979e+04,0.000000,96.955069,0.000000,0.000000,3.044931,0.000000,0.000000,POINT (422147.974 6456591.214)
455,729017,S',t₁30-50/sl,1000.0,400.0,25,25,50,0,1000.0,...,0.000000,7.468049e+04,0.000000,80.679711,0.000000,19.320289,0.000000,0.000000,0.000000,POINT (702837.160 6431193.404)
17,97248,GI,l,1000.0,1000.0,90,5,5,0,NaN,...,0.000000,2.964682e+05,0.000000,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000,POINT (563749.205 6460467.882)
40,147436,Gk,r₂ls₁30-40/p,1000.0,350.0,65,20,15,15,1000.0,...,96381.385456,1.625018e+05,0.000000,40.637549,0.051487,0.000000,0.000000,0.000000,59.310964,POINT (384602.515 6477732.442)
218,329246,Ko,ls₁40/r₃ls₁,1000.0,400.0,65,20,15,0,1000.0,...,2629.539128,1.006566e+05,0.046007,95.646003,0.000000,0.000000,1.927158,0.000000,2.612386,POINT (445182.001 6478714.976)
71,208183,Go1,ls₂50-85/+ls₂,1000.0,675.0,55,30,15,0,1000.0,...,0.000000,2.179370e+05,0.000000,99.557109,0.000000,0.442891,0.000000,0.000000,0.000000,POINT (546832.495 6475452.919)
131,257910,Kh',r₂ls₁2-5/p,1000.0,35.0,65,20,15,15,1000.0,...,0.000000,6.058579e+04,4.012988,63.381739,32.605273,0.000000,0.000000,0.000000,0.000000,POINT (507280.850 6500636.442)
166,261683,Kh''g,r₂ls₁20-30/p,1000.0,250.0,65,20,15,15,1000.0,...,30390.973133,3.738394e+05,0.000000,91.660771,0.000000,0.209810,0.000000,0.000000,8.129419,POINT (457261.792 6493412.312)
214,325259,Ko,v⁰₁ls₂60/p,1000.0,600.0,55,30,15,6,1000.0,...,0.000000,3.888291e+04,0.000000,89.794374,6.740802,0.000000,3.464824,0.000000,0.000000,POINT (496641.983 6496707.991)
461,739365,S''',t₁80/t₂50-70,1400.0,800.0,25,25,50,0,1400.0,...,0.000000,5.808664e+05,0.000000,86.066097,0.000000,13.933903,0.000000,0.000000,0.000000,POINT (687871.779 6565109.821)
108,240564,K,r₂ls25-28/r₃ls,1000.0,265.0,55,30,15,15,1000.0,...,662.925661,1.525388e+05,99.565405,0.000000,0.000000,0.000000,0.000000,0.000000,0.434595,POINT (566268.904 6570644.748)
333,453331,LIIg,l150,1500.0,1500.0,90,5,5,0,NaN,...,2961.521502,1.522520e+05,0.000000,86.405040,3.570985,0.877395,7.201435,0.000000,1.945145,POINT (495462.156 6550329.158)
48,152364,Gkr,ls₂20/r₄ls₂20/p,1000.0,200.0,55,30,15,0,400.0,...,0.000000,4.046365e+04,0.000000,100.000000,0.000000,0.000000,0.000000,0.000000,0.000000,POINT (544671.151 6523479.591)

In [22]:
cleaned_data.info()

<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 745432 entries, 0 to 745431
Data columns (total 24 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   orig_fid    745432 non-null  int64
 1   est_soilty  745432 non-null  object
 2   est_txcode  745426 non-null  object
 3   zmx         745432 non-null  float64
 4   z1          745432 non-null  float64
 5   sand1       745432 non-null  int64
 6   silt1       745432 non-null  int64
 7   clay1       745432 non-null  int64
 8   rock1       745432 non-null  int64
 9   z2          359147 non-null  float64
 10  sand2       359147 non-null  float64
 11  silt2       359147 non-null  float64
 12  clay2       359147 non-null  float64
 13  rock2       359147 non-null  float64
 14  z3          19851 non-null   float64
 15  sand3       19851 non-null   float64
 16  silt3       19851 non-null   float64
 17  clay3       19851 non-null   float64
 18  rock3       19851 non-null   float64
 19  z4          70 non-null      float64
 20  sand4       70 non-null      float64
 21  silt4       70 non-null      float64
 22  clay4       70 non-null      float64
 23  rock4       70 non-null      float64
dtypes: float64(17), int64(5), object(2)
memory usage: 136.5+ MB